- name: Create VPC & Subnet in GCP
  hosts: localhost
  gather_facts: no
  vars:
    project_id: <project id>
    service_account_file: ~/path/to/.json

  tasks:
    - name: Create a VPC network
      google.cloud.gcp_compute_network:
        name: my-vpc-network
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        auto_create_subnetworks: false
        state: present
      register: network

    - name: create a subnetwork
      google.cloud.gcp_compute_subnetwork:
        name: "{{item.name}}"
        region: "{{item.region}}"
        network: "{{ network }}"
        ip_cidr_range: "{{item.cidr}}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: present
      loop: 
        - { name: "subnet-a", region: "us-west1", cidr: "10.10.1.0/24" }
        - { name: "subnet-b", region: "us-central1", cidr: "10.20.1.0/24" }
        - { name: "subnet-c", region: "us-central1", cidr: "10.30.1.0/24" }

    - name: create a firewall
      google.cloud.gcp_compute_firewall:
        name: "{{item.name}}"
        network: "{{ network }}"
        allowed: "{{item.allowed}}"
        source_ranges: "{{item.source_ranges}}"
        project: "{{project_id}}"
        auth_kind: serviceaccount
        service_account_file: "{{service_account_file}}"
        state: present 
      loop:
        - name: "allow-ssh"
          allowed:
            - ip_protocol: tcp
              ports: ["22"]
          source_ranges: ["0.0.0.0/0"]

        - name: "allow-http"
          allowed:
            - ip_protocol: tcp
              ports: ["80"]
          source_ranges: ["0.0.0.0/0"]

        - name: "allow-icmp"
          allowed:
            - ip_protocol: icmp
          source_ranges: ["0.0.0.0/0"]
